version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ../Payload
      dockerfile: Dockerfile.back
    container_name: payload
    environment:
      - DATABASE_URI=mongodb://mongo:27017/tom
      - PAYLOAD_SECRET=1574
    ports:
      - "3000:3000"
    volumes:
      - ../Payload:/app
      - /app/node_modules
    depends_on:
      - mongo



  frontend:
    build:
      context: ../FrontEnd/frontend
      dockerfile: Dockerfile.front
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:  
      - ../FrontEnd/frontend:/app
    depends_on:
      - backend


volumes:
  mongo_data:
